title: Explore Bioinformatics
description: Bioinformatics projects, tutorials, & more!
theme: just-the-docs
color_scheme: light

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
